### ISSUE TITLE
Client side support

### ISSUE THREAD

**Issue by debris** [debris/jsonrpc-core#7]
Client side support requires:
- [x] implementing `Serialize` trait for:
  - [x] `MethodCall`
  - [x] `Notification`
  - [x] `Call`
  - [x] `Request`
- [x] implementing `Deserialize` trait for: 
  - [x] `Success`
  - [x] `Failure`
  - [x] `Output`
  - [x] `Response`
  - [x] `Params`
- [x] comprehensive tests for newly added code (especially deserialization). 
- [ ] easy to use Request Builder (maybe utilizing builder pattern? not sure about this one, it's optional)

**Comment by Latrasis** [comment]
Since the `Params` struct already has the `Deserialization` trait applied, does this mean it's already done? Or is there something else missing?

**Comment by debris** [comment]
It does mean it's already done.
